
http://0.0.0.0:9999/purchaseCard

{
  "method": "POST",
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "url": "http://0.0.0.0:9999/purchaseCard",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "application/json;charset=utf-8"
  },
  "data": "{'card_type': 'virtual', 'card_issuer': 'Visa', 'user_id': 12345}",
  "timeout": {}
}



